# Study du gap entre pruning et sans pruning

In [1]:
import numpy as np 
import pandas as pd
from fastsdp_tools import get_project_path
import matplotlib.pyplot as plt

tab_with_all_pruning = pd.read_csv(get_project_path("results/benchmark/6x100-0.026/11_14_17h27_57s_SDPu-full-pruning-RLT=60/results.csv"))
#tab_with_all_pruning = tab_with_all_pruning[(tab_with_all_pruning['status']!='trivially_solved') & (tab_with_all_pruning['model']!='LP')].copy()
# #tab1 = tab1[tab1["data_index"]<29].copy()
# tab2 = pd.read_csv(get_project_path("results/benchmark/9x100-0.026/09_18_15h42_46s_SDPu-full-pruning-RLT=100-28-56-96-97/results.csv"))
#tab3 = pd.read_csv(get_project_path("£results/benchmark/9x200-0.015/09_23_08h54_49s_SDPt-RLT=0.2-55-99/results.csv"))
#tab4 = pd.read_csv(get_project_path("results/benchmark/9x200-0.015/11_05_23h21_56s_SDPt-RLT=0.2-35-44-84-99/results.csv"))  
# # # #tab5 = pd.read_csv(get_project_path("results/benchmark/9x100-0.026/FINAL/SDP-IP/results-60-99.csv"))
# # # # tab = pd.concat([tab1,tab2]µ)
# # #tab2 = tab2[tab2["data_index"]<79].copy();
# tab = pd.concat([tab1, tab2]).reset_index(drop=True)

tab_without_pruning = pd.read_csv(get_project_path("results/benchmark/6x200-0.015/FINAL/SDPu/results-partial-pruning-RT=0.5.csv"))
# #tab_without_pruning = tab_without_pruning[tab_without_pruning['status']!='trivially_solved'].copy()
# Nb_neurons = 9*200

# nb_stables_study = pd.read_csv(get_project_path("results/benchmark/6x200-0.015/FINAL/SDPu/results-full-pruning-RT=0.6.csv"))
# nb_stables_study["Stable"] = nb_stables_study["Number_actives_stable"] + nb_stables_study["Number_inactives_stable"]
# nb_stables_study["Unstable"] = Nb_neurons - nb_stables_study["Stable"]

In [4]:
tab_with_all_pruning["status"]

0     trivially_solved
1     trivially_solved
2     trivially_solved
3     trivially_solved
4     trivially_solved
5     trivially_solved
6     trivially_solved
7                    0
8     trivially_solved
9     trivially_solved
10    trivially_solved
11    trivially_solved
12                   0
13                   0
14    trivially_solved
15    trivially_solved
16                   0
17    trivially_solved
18                   0
19    trivially_solved
20    trivially_solved
21    trivially_solved
22                   0
23                   0
24    trivially_solved
25    trivially_solved
26                   0
27    trivially_solved
28                   0
29                   0
30    trivially_solved
31    trivially_solved
32    trivially_solved
33    trivially_solved
34    trivially_solved
35                   0
36    trivially_solved
37    trivially_solved
38                   0
39                   0
Name: status, dtype: object

In [2]:
tab_without_pruning[tab_without_pruning["data_index"]==61]

,Unnamed: 0,LAST_LAYER,MATRIX_BY_LAYERS,McC_betaz_logits,Nb_constraints,Nb_stable_actives,Nb_stable_inactives,RLT,RLT_prop,Tij,...,label_predicted,model,network,optimal_value,pretreatment_time,primal_obj_value,status,target,time,triangularization
49,49,False,True,True,168342.0,0,709,True,0.5,True,...,6,UntargetedSDP,6x200,-0.011239,134.084445,0.015682,0,NaN,1536.497012,True

In [3]:
tab_with_all_pruning = tab_with_all_pruning[tab_with_all_pruning["status"]!='trivially_solved'][["data_index", "optimal_value", "time", "bound_time", "status"]].copy()
tab_without_pruning = tab_without_pruning[tab_without_pruning["status"]!='trivially_solved'][["data_index", "optimal_value", "time", "bound_time", "status"]].copy()

In [4]:
tab_with_all_pruning[tab_with_all_pruning["data_index"]==60]

Empty DataFrame
Columns: [data_index, optimal_value, time, bound_time, status]
Index: []

In [5]:

data_index_all_pruning = tab_with_all_pruning['data_index'].values
data_index_no_pruning = tab_without_pruning['data_index'].values    
print("Number of examples with full pruning:", len(set(data_index_all_pruning)))
print("Number of examples with no pruning:", len(set(data_index_no_pruning)))

print('Data indices in no pruning but not in full pruning:', set(data_index_no_pruning) - set(data_index_all_pruning))
for i in data_index_no_pruning:
    if i not in data_index_all_pruning:
        print("Missing index in full pruning results:", i)
    
for i in data_index_all_pruning:
    if i not in data_index_no_pruning:
        print("Missing index in full pruning results:", i)

Number of examples with full pruning: 36
Number of examples with no pruning: 36
Data indices in no pruning but not in full pruning: set()

In [6]:
if "RLT_prop" in tab_with_all_pruning.columns:
    tab_with_all_pruning["RLT_prop"] = tab_with_all_pruning["RLT_prop"].fillna(0)
    RLT_prop = tab_with_all_pruning["RLT_prop"].unique()
    
    print("RLT_prop:", RLT_prop)
    #RLT_props = [0, 0.1, 0.3, 0.5]
    #tab = tab[tab["RLT_prop"].isin(RLT_props)].copy()
    

tab_with_all_pruning["total_time"] = tab_with_all_pruning["time"] + tab_with_all_pruning["bound_time"]
#tab_with_all_pruning["target"] = tab_with_all_pruning["target"].fillna("unknown")

if "RLT_prop" in tab_without_pruning.columns:
    tab_without_pruning["RLT_prop"] = tab_without_pruning["RLT_prop"].fillna(0)
    RLT_prop = tab_without_pruning["RLT_prop"].unique()
    
    print("RLT_prop:", RLT_prop)
    #RLT_props = [0, 0.1, 0.3, 0.5]
    #tab = tab[tab["RLT_prop"].isin(RLT_props)].copy()
    

tab_without_pruning["total_time"] = tab_without_pruning["time"] + tab_without_pruning["bound_time"]
tab_without_pruning["robust"] = (tab_without_pruning["optimal_value"] >= 0) | (tab_without_pruning["status"]=="trivially_solved")

In [7]:
tab_with_all_pruning["optimal_value_partial_pruning"] = tab_with_all_pruning.apply(lambda row : tab_without_pruning[tab_without_pruning["data_index"]==row["data_index"]]["optimal_value"].values[0], axis=1)

In [8]:
tab_with_all_pruning["gap_pruning"] = (tab_with_all_pruning["optimal_value"] - tab_with_all_pruning["optimal_value_partial_pruning"])
tab_with_all_pruning["rel_gap_pruning"] = tab_with_all_pruning["gap_pruning"] / np.abs(tab_with_all_pruning["optimal_value_partial_pruning"])
tab_with_all_pruning["robust_full_puning"] = (tab_with_all_pruning["optimal_value"] >= 0) 
tab_with_all_pruning["robust_partial_pruning"] = (tab_with_all_pruning["optimal_value_partial_pruning"] >= 0)

In [19]:
tab_with_all_pruning["rel_gap_pruning"].min()

-74.74840252855292

In [21]:
tab_with_all_pruning.shape

(36, 11)

In [32]:
tab_with_all_pruning[~tab_with_all_pruning["robust_partial_pruning"] & tab_with_all_pruning["robust_full_puning"]]["gap_pruning"].mean()    #60, 70, 72, 91, 98

0.9294622781630051